version: '2'
services:
    casadocodigo-mysql:
        image: mysql:5.7.26
        restart: always
        container_name: casadocodigo-mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3306:3306
    casadocodigo-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: casadocodigo-phpmyadmin
        ports:
            - "8085:80"
        environment:
            - PMA_HOST=casadocodigo-mysql
        links:
            - casadocodigo-mysql
        depends_on:
          - casadocodigo-mysql
